# This file is part of the YesWiki Extension accountactivationbyemail.
# Authors : see README.md file that was distributed with this source code.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
parameters:
  signup_email_activation: true # Activate the signup activation mail process
  user_activation_key_length: 20 # length of activation/inactivation keys
  accountactivationbyemail_editable_config_params:
    - 'signup_email_activation'
    - 'user_activation_key_length'

services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Accountactivationbyemail\Service\:
    resource: 'services/*'

  YesWiki\Accountactivationbyemail\Controller\:
    resource: 'controllers/*'

  YesWiki\Accountactivationbyemail\Controller\AuthController:
    decorates: YesWiki\Core\Controller\AuthController
    decoration_on_invalid: ignore

  YesWiki\Accountactivationbyemail\Controller\UserController:
    decorates: YesWiki\Core\Controller\UserController
    decoration_on_invalid: ignore